"""add_code_field_to_findings

Revision ID: 5ef468439cbe
Revises: 73fd007be871
Create Date: 2025-08-21 23:58:43.508210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef468439cbe'
down_revision: Union[str, None] = '73fd007be871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('code', sa.String(), nullable=True))
    op.alter_column('findings', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('findings', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('findings', 'code')
    # ### end Alembic commands ###
