"""fix pull request model fields

Revision ID: e771a7b7b228
Revises: de662ebb171b
Create Date: 2025-08-19 13:53:35.197058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e771a7b7b228'
down_revision: Union[str, None] = 'de662ebb171b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('pr_github_id', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('tool', sa.String(length=100), nullable=True))
    op.add_column('findings', sa.Column('path', sa.String(length=500), nullable=True))
    op.add_column('findings', sa.Column('line', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_findings_id'), 'findings', ['id'], unique=False)
    op.create_index(op.f('ix_findings_pr_github_id'), 'findings', ['pr_github_id'], unique=False)
    op.drop_column('findings', 'rule_id')
    op.drop_column('findings', 'type')
    op.drop_column('findings', 'pr_id')
    op.drop_column('findings', 'file_path')
    op.drop_column('findings', 'payload')
    op.drop_column('findings', 'line_number')
    op.add_column('pull_requests', sa.Column('pr_number', sa.Integer(), nullable=True))
    op.add_column('pull_requests', sa.Column('action', sa.String(length=50), nullable=True))
    op.alter_column('pull_requests', 'github_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pull_requests', 'repo_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('pull_requests_github_id_key', 'pull_requests', type_='unique')
    op.create_index(op.f('ix_pull_requests_github_id'), 'pull_requests', ['github_id'], unique=True)
    op.drop_column('pull_requests', 'opened_at')
    op.drop_column('pull_requests', 'author')
    op.drop_column('pull_requests', 'first_response_ms')
    op.add_column('review_comments', sa.Column('github_id', sa.Integer(), nullable=True))
    op.add_column('review_comments', sa.Column('pr_github_id', sa.Integer(), nullable=True))
    op.add_column('review_comments', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('review_comments', sa.Column('path', sa.String(length=500), nullable=True))
    op.add_column('review_comments', sa.Column('line', sa.Integer(), nullable=True))
    op.add_column('review_comments', sa.Column('position', sa.Integer(), nullable=True))
    op.drop_constraint('review_comments_github_comment_id_key', 'review_comments', type_='unique')
    op.create_index(op.f('ix_review_comments_github_id'), 'review_comments', ['github_id'], unique=True)
    op.create_index(op.f('ix_review_comments_id'), 'review_comments', ['id'], unique=False)
    op.create_index(op.f('ix_review_comments_pr_github_id'), 'review_comments', ['pr_github_id'], unique=False)
    op.drop_column('review_comments', 'adopted')
    op.drop_column('review_comments', 'content')
    op.drop_column('review_comments', 'github_comment_id')
    op.drop_column('review_comments', 'severity')
    op.drop_column('review_comments', 'pr_id')
    op.drop_column('review_comments', 'file_path')
    op.drop_column('review_comments', 'line_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_comments', sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('review_comments', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('review_comments', sa.Column('pr_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('review_comments', sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('review_comments', sa.Column('github_comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('review_comments', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('review_comments', sa.Column('adopted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_review_comments_pr_github_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_github_id'), table_name='review_comments')
    op.create_unique_constraint('review_comments_github_comment_id_key', 'review_comments', ['github_comment_id'])
    op.drop_column('review_comments', 'position')
    op.drop_column('review_comments', 'line')
    op.drop_column('review_comments', 'path')
    op.drop_column('review_comments', 'body')
    op.drop_column('review_comments', 'pr_github_id')
    op.drop_column('review_comments', 'github_id')
    op.add_column('pull_requests', sa.Column('first_response_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pull_requests', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pull_requests', sa.Column('opened_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pull_requests_github_id'), table_name='pull_requests')
    op.create_unique_constraint('pull_requests_github_id_key', 'pull_requests', ['github_id'])
    op.alter_column('pull_requests', 'repo_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pull_requests', 'github_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pull_requests', 'action')
    op.drop_column('pull_requests', 'pr_number')
    op.add_column('findings', sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('findings', sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('findings', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('findings', sa.Column('pr_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('findings', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('findings', sa.Column('rule_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_findings_pr_github_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_id'), table_name='findings')
    op.drop_column('findings', 'line')
    op.drop_column('findings', 'path')
    op.drop_column('findings', 'tool')
    op.drop_column('findings', 'pr_github_id')
    # ### end Alembic commands ###
