version: '3.8'

services:
  api:
    build: 
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://codexlens:password@db:5432/codexlens
      - REDIS_URL=redis://redis:6379/0
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    volumes:
      - ../apps:/app/apps
    depends_on:
      - db
      - redis
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    environment:
      - DATABASE_URL=postgresql://codexlens:password@db:5432/codexlens
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ../apps:/app/apps
    depends_on:
      - db
      - redis
    command: celery -A apps.worker.worker worker --loglevel=info

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=codexlens
      - POSTGRES_USER=codexlens
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: